from .farmacia import InventarioFarmacia
from .manager import Manager
from .terapias import Terapias
from .jornadas import Jornadas
from .pacientes import Pacientes
from .carrito import Carrito
from .combos import Combos
from .usuario import Usuarios
from .cierre import Cierre
from .vitacora import Vitacora
from .ventas import Ventas
