from .main_view import VentanaPrincipal
from .ventanaFuncional import VentanaFuncional
from .ModificarMedicamentos import AgregarMedi
from .descuentosMedi import DescuentoMedi
from .contraseña import Contrasena
from .controller import Controller
from .Jornadas import jornadas
from .ModificarTerapia import AgregarTerapia
from .ModificarPacientes import AgregarPacientes
from .ModificarCombos import AgregarCombos
from .ModificarUsuarios import AgregarUsuarios
from .ModificarCierre import AgregarCierre
from .ModificarExistencia import Existencias
from .datos_cliente import DatosCliente
from .Modificar_vitacora import AgregarVitacora
from .lab import Lab
from .presentacion import Presen
from .pago_dividido import DialogoPagoDividido
from .contra_desc import Contra
from .medi_ter import DialogoTerapia
from .medi_jorda import Dialogo_jorda
from .contra_total import Contra_total
from .codigoAnulacion import CodigoAnulacion
from .modificar_ventas import Metodos_ventas
from .detalles import Detalles
from .efectivo import CashRegisterApp
from .gastos import GastosApp
from .tarjeta import IngresoTarjetaApp
from .trasfere import IngresoTransferenciaApp
from .cierre_crudo import CierreApp
from .cheques import RegistroCheques
from .Reporte import AplicacionReporteFinanciero
from .comision import VentasComisionesApp
